name: Sync Files
on: [push, workflow_dispatch]
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - uses: tibdex/github-app-token@v1.0.2
        id: generate-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Run GitHub File Sync
        uses: BetaHuhn/repo-file-sync-action@v1.14.0
        with:
          GH_INSTALLATION_TOKEN: ${{ steps.generate-token.outputs.token }}
          COMMIT_BODY: "Signed-off-by: common-config[bot]"
          GIT_EMAIL: <>
          GIT_USERNAME: Common-config Bot
          
