name: Sync Files
on: [push, workflow_dispatch]
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run GitHub File Sync
        uses: xanjohns/repo-file-sync-action@create-fork-feature
        with:
          GH_PAT: ${{ secrets.GH_PAT }}
          COMMIT_BODY: "Signed-off-by: common-config[bot]"
          FORK: xanjohns
          
